version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# Anchors to prevent forgetting to update a version
os_version: &os_version ubuntu24
baselibs_version: &baselibs_version v8.19.0
bcs_version: &bcs_version v12.0.0
tag_build_arg_name: &tag_build_arg_name fv3version

orbs:
  ci: geos-esm/circleci-tools@5

workflows:
  build-test:
    jobs:

      # Build GEOSfvdycore
      - ci/build:
          name: build-GEOSfvdycore-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              # ifx has issues with FMS
              #compiler: [gfortran, ifort, ifx]
              compiler: [gfortran, ifort]
              fv_precision: ["R4", "R8"]
          baselibs_version: *baselibs_version
          repo: GEOSfvdycore
          mepodevelop: false
          persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra

      # Run FV3 standalone
      - ci/run_fv3:
          name: run-FV3-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>-with-GEOSfvdycore
          context:
            - docker-hub-creds
          matrix:
            parameters:
              # ifx has issues with FMS
              #compiler: [gfortran, ifort, ifx]
              compiler: [gfortran, ifort]
              fv_precision: ["R4", "R8"]
          baselibs_version: *baselibs_version
          requires:
            - build-GEOSfvdycore-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          repo: GEOSfvdycore

  # Build and publish docker images
  build-and-publish-docker:
    when:
      equal: [ "release", << pipeline.parameters.GHA_Event >> ]
    jobs:
      - ci/publish_docker:
          filters:
            tags:
              only: /^v.*$/
          name: publish-ifort-docker-image
          context:
            - docker-hub-creds
            - ghcr-creds
          os_version: *os_version
          baselibs_version: *baselibs_version
          container_name: geosfvdycore
          mpi_name: intelmpi
          mpi_version: "2021.13"
          compiler_name: ifort
          compiler_version: "2021.13"
          image_name: geos-env
          tag_build_arg_name: *tag_build_arg_name
          resource_class: xlarge
      #- ci/publish_docker:
          #filters:
            #tags:
              #only: /^v.*$/
          #name: publish-ifx-docker-image
          #context:
            #- docker-hub-creds
            #- ghcr-creds
          #os_version: *os_version
          #baselibs_version: *baselibs_version
          #container_name: geosfvdycore
          #mpi_name: intelmpi
          #mpi_version: "2021.14"
          #compiler_name: ifx
          #compiler_version: "2025.0"
          #image_name: geos-env
          #tag_build_arg_name: *tag_build_arg_name
          #resource_class: xlarge
      - ci/publish_docker:
          filters:
            tags:
              only: /^v.*$/
          name: publish-gcc-docker-image
          context:
            - docker-hub-creds
            - ghcr-creds
          os_version: *os_version
          baselibs_version: *baselibs_version
          container_name: geosfvdycore
          mpi_name: openmpi
          mpi_version: 5.0.5
          compiler_name: gcc
          compiler_version: 14.2.0
          image_name: geos-env-mkl
          tag_build_arg_name: *tag_build_arg_name
          resource_class: xlarge
