version: 2.1

executors:
  gcc-build-env:
    docker:
      - image: gmao/ubuntu20-geos-env-mkl:6.0.13-openmpi_4.0.4-gcc_10.2.0
    environment:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    resource_class: xlarge

jobs:
  build:
    executor: gcc-build-env
    working_directory: /root/project
    steps:
      - checkout
      - run:
          name: "Versions etc"
          command: mpirun --version && gfortran --version && echo $BASEDIR && pwd && ls
      - run:
          name: "Mepo clone external repos"
          command: |
            mepo clone
            mepo status
      - run:
          name: "CMake"
          command: |
            mkdir build
            cd build
            cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF
      - run:
          name: "Build and install"
          command: |
            cd build
            make -j"$(nproc)" install

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build

