version: 2.1

# Anchor to prevent forgetting to update a version
baselibs_version: &baselibs_version v7.5.0

orbs:
  ci: geos-esm/circleci-tools@1

workflows:
  build-test:
    jobs:
      - ci/build:
          name: build-GEOSfvdycore-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort, gfortran]
          baselibs_version: *baselibs_version
          repo: GEOSfvdycore
          mepodevelop: false
          persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra
      - ci/run_fv3:
          name: run-FV3-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort]
          baselibs_version: *baselibs_version
          requires:
            - build-GEOSfvdycore-on-<< matrix.compiler >>
          repo: GEOSfvdycore
