name: Enforce PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  require-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      with:
        REQUIRED_LABELS_ANY: "0 diff,0 diff trivial,Non 0-diff,0 diff structural,0-diff trivial,Not 0-diff,0-diff,automatic,0-diff uncoupled,dependencies"
        BANNED_LABELS: "Contingent - DNA,Needs Lead Approval,Contingent -- Do Not Approve"
        BANNED_LABELS_DESCRIPTION: "The label ${bannedLabel.name} is blocking this PR from being merged"

