name: Enforce PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  require-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.1
      with:
        REQUIRED_LABELS_ANY: "0 diff,0 diff trivial,Non 0-diff,0 diff structural"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['0 diff', '0 diff trivial', 'Non 0-diff', '0 diff structural']"
        BANNED_LABELS: "Contingent - DNA,Needs Lead Approval"

