name: Build Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.json"
      - "ChangeLog-PreJason.txt"
      - "parallel_build.csh"
      - ".github/CODEOWNERS"
      - ".codebuild/**"
      - ".circleci/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build_fv3:
    strategy:
      matrix:
        compiler: [ifort, gfortran-14, gfortran-15]
        build-type: [Debug]
    uses: GEOS-ESM/CI-workflows/.github/workflows/geosgcm_build_tests.yml@project/geosgcm
    with:
      compiler: ${{ matrix.compiler }}
      cmake-build-type: ${{ matrix.build-type }}

  spack_build:
    uses: GEOS-ESM/CI-workflows/.github/workflows/spack_gcc_build.yml@project/geosgcm
    secrets:
      BUILDCACHE_USERNAME: ${{ secrets.BUILDCACHE_USERNAME }}
      BUILDCACHE_TOKEN: ${{ secrets.BUILDCACHE_TOKEN }}